services:
  - type: web
    name: property-price-predictor
    env: python
    buildCommand: ""
    startCommand: "python app.py"
    envVars:
      - key: FLASK_ENV
        value: development
